Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# change the index values below to pick molecules with and without a carbonyl
idx_hasCarbonyl=1
idx_notCarbonyl=0
# get the data for the two molecules
hasCarbonyl=train.set_index('name').iloc[idx_hasCarbonyl,3:]
notCarbonyl=train.set_index('name').iloc[idx_notCarbonyl,3:] 
# plot the spectra
fig = go.Figure()
fig.add_trace(go.Scatter(x=hasCarbonyl.index, y=hasCarbonyl, name=hasCarbonyl.name,mode='markers'))
fig.add_trace(go.Scatter(x=notCarbonyl.index, y=notCarbonyl,name=notCarbonyl.name,mode='markers'))
fig.update_layout(title='Intensities over frequency',title_x=0.5)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[9], line 8[0m
[1;32m      6[0m notCarbonyl[38;5;241m=[39mtrain[38;5;241m.[39mset_index([38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m)[38;5;241m.[39miloc[idx_notCarbonyl,[38;5;241m3[39m:] 
[1;32m      7[0m [38;5;66;03m# plot the spectra[39;00m
[0;32m----> 8[0m fig [38;5;241m=[39m [43mgo[49m[38;5;241m.[39mFigure()
[1;32m      9[0m fig[38;5;241m.[39madd_trace(go[38;5;241m.[39mScatter(x[38;5;241m=[39mhasCarbonyl[38;5;241m.[39mindex, y[38;5;241m=[39mhasCarbonyl, name[38;5;241m=[39mhasCarbonyl[38;5;241m.[39mname,mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mmarkers[39m[38;5;124m'[39m))
[1;32m     10[0m fig[38;5;241m.[39madd_trace(go[38;5;241m.[39mScatter(x[38;5;241m=[39mnotCarbonyl[38;5;241m.[39mindex, y[38;5;241m=[39mnotCarbonyl,name[38;5;241m=[39mnotCarbonyl[38;5;241m.[39mname,mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mmarkers[39m[38;5;124m'[39m))

[0;31mNameError[0m: name 'go' is not defined

