Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import Python libraries to work with SciServer (see http://www.sciserver.org/docs/sciscript-python/)

import SciServer.CasJobs as CasJobs # query with CasJobs, the primary database for the SDSS
import SciServer.SkyServer as SkyServer # show individual objects through SkyServer
import SciServer.SciDrive           # read/write to/from SciDrive, cloud-based storage for your work
import numpy as np                  # standard Python library for math operations
import pandas                       # package for structuring and visualizing data
import matplotlib.pyplot as plt     # package for graphing and visualization 
print('SciServer libraries imported')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[8], line 3[0m
[1;32m      1[0m [38;5;66;03m# Import Python libraries to work with SciServer (see http://www.sciserver.org/docs/sciscript-python/)[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mSciServer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCasJobs[39;00m [38;5;28;01mas[39;00m [38;5;21;01mCasJobs[39;00m [38;5;66;03m# query with CasJobs, the primary database for the SDSS[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mSciServer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSkyServer[39;00m [38;5;28;01mas[39;00m [38;5;21;01mSkyServer[39;00m [38;5;66;03m# show individual objects through SkyServer[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mSciServer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSciDrive[39;00m           [38;5;66;03m# read/write to/from SciDrive, cloud-based storage for your work[39;00m

[0;31mModuleNotFoundError[0m: No module named 'SciServer'

