Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import relevant libraries

import SciServer.CasJobs as CasJobs # query with CasJobs
import SciServer.SkyServer as SkyServer # look up objects and generate images
import pandas as pd # data analysis 
import numpy as np # more data analysis
from matplotlib import pyplot as plt # another plotting library
from astropy.constants import c # useful constants
from astropy import units as u # useful for unit conversions
import astroML # enables plotting sdss spectrum
from astroML.datasets import fetch_sdss_spectrum
from astropy.io import ascii
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;66;03m# Import relevant libraries[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mSciServer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mCasJobs[39;00m [38;5;28;01mas[39;00m [38;5;21;01mCasJobs[39;00m [38;5;66;03m# query with CasJobs[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mSciServer[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSkyServer[39;00m [38;5;28;01mas[39;00m [38;5;21;01mSkyServer[39;00m [38;5;66;03m# look up objects and generate images[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m [38;5;66;03m# data analysis [39;00m

[0;31mModuleNotFoundError[0m: No module named 'SciServer'

